# -*- coding: utf-8 -*-
"""Dentes Hígidos e Não Hígidos - A. R. M..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ioomRrrWpLxrayFAm68aK6fCsnR7tOQo
"""

import matplotlib.pyplot as plt

# Dados
labels = ['Hígido', 'Não Hígido']
sizes_superior = [92.86, 7.14]
sizes_inferior = [92.86, 7.14]
colors = ['#66b3ff','#ff6666']

# Gráfico da Arcada Superior
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.pie(sizes_superior, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.title('Arcada Superior')

# Gráfico da Arcada Inferior
plt.subplot(1, 2, 2)
plt.pie(sizes_inferior, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.title('Arcada Inferior')

# Exibindo os gráficos
plt.tight_layout()
plt.show()